export const typeStyles: Record<string, string> = {
    Normal:   "bg-[#a8a878] text-black px-4 py-1 rounded text-sm font-light",
    Feu:     "bg-[#f08030] text-white px-4 py-1 rounded text-sm font-light",
    Eau:    "bg-[#6890f0] text-white px-4 py-1 rounded text-sm font-light",
    Électrik: "bg-[#f8d030] text-black px-4 py-1 rounded text-sm font-light",
    Plante:   "bg-[#78c850] text-black px-4 py-1 rounded text-sm font-light",
    Glace:      "bg-[#98d8d8] text-black px-4 py-1 rounded text-sm font-light",
    Combat: "bg-[#c03028] text-white px-4 py-1 rounded text-sm font-light",
    Poison:   "bg-[#a040a0] text-white px-4 py-1 rounded text-sm font-light",
    Sol:   "bg-[#e0c068] text-black px-4 py-1 rounded text-sm font-light",
    Vol:   "bg-[#a890f0] text-black px-4 py-1 rounded text-sm font-light",
    Psy:  "bg-[#f85888] text-white px-4 py-1 rounded text-sm font-light",
    Insecte:      "bg-[#a8b820] text-black px-4 py-1 rounded text-sm font-light",
    Roche:     "bg-[#b8a038] text-white px-4 py-1 rounded text-sm font-light",
    Spectre:    "bg-[#705898] text-white px-4 py-1 rounded text-sm font-light",
    Dragon:   "bg-[#7038f8] text-white px-4 py-1 rounded text-sm font-light",
};
