export const typeStyles: Record<string, string> = {
    normal:   "bg-[#a8a878] text-black px-2 py-1 rounded text-sm font-medium",
    fire:     "bg-[#f08030] text-white px-2 py-1 rounded text-sm font-medium",
    water:    "bg-[#6890f0] text-white px-2 py-1 rounded text-sm font-medium",
    electric: "bg-[#f8d030] text-black px-2 py-1 rounded text-sm font-medium",
    grass:    "bg-[#78c850] text-black px-2 py-1 rounded text-sm font-medium",
    ice:      "bg-[#98d8d8] text-black px-2 py-1 rounded text-sm font-medium",
    fighting: "bg-[#c03028] text-white px-2 py-1 rounded text-sm font-medium",
    poison:   "bg-[#a040a0] text-white px-2 py-1 rounded text-sm font-medium",
    ground:   "bg-[#e0c068] text-black px-2 py-1 rounded text-sm font-medium",
    flying:   "bg-[#a890f0] text-black px-2 py-1 rounded text-sm font-medium",
    psychic:  "bg-[#f85888] text-white px-2 py-1 rounded text-sm font-medium",
    bug:      "bg-[#a8b820] text-black px-2 py-1 rounded text-sm font-medium",
    rock:     "bg-[#b8a038] text-white px-2 py-1 rounded text-sm font-medium",
    ghost:    "bg-[#705898] text-white px-2 py-1 rounded text-sm font-medium",
    dragon:   "bg-[#7038f8] text-white px-2 py-1 rounded text-sm font-medium",
    dark:     "bg-[#705848] text-white px-2 py-1 rounded text-sm font-medium",
    steel:    "bg-[#b8b8d0] text-black px-2 py-1 rounded text-sm font-medium",
    fairy:    "bg-[#ee99ac] text-black px-2 py-1 rounded text-sm font-medium",
};
